In [4]:
#crea un array lleno de ceros con 8 espacios 
import numpy as np 
array_1 = np.zeros((8))
#convertir todos los ceros en 2
array_1[array_1 == 0] = 2
print(array_1)

[2. 2. 2. 2. 2. 2. 2. 2.]


In [33]:
#crea un array que contenga todos los números pares del 1 al 10 
array_2 = np.arange(2,11,2)
print(array_2)
#sumar todos los números del arraty usando un bucle 
suma = 0
for num in array_2:
    suma += num
print(f'la suma de todos los números usando un bucle es {suma}')
#sumar todos los números usando una funcion de numpy
suma_2 = array_2.sum()
print(f'la suma de los elementos del array usando una funcion de numpy es {suma_2}')
#revertir el array y guardarlo en un a variable independiente 
array_revertido = array_2[::-1]
print(f'array_revertido: {array_revertido}')
#encontrar elementos comunes entre los tres arrays 
elementos_comunes1 = np.intersect1d(array_1,array_2)
elementos_comunes2 = np.intersect1d(array_2,array_revertido)
print(elementos_comunes1)
print(elementos_comunes2)

[ 2  4  6  8 10]
la suma de todos los números usando un bucle es 30
la suma de los elementos del array usando una funcion de numpy es 30
array_revertido: [10  8  6  4  2]
[2.]
[ 2  4  6  8 10]


In [34]:
#crea un array lleno de 1s con la longitud dada por el usuario 
longitud = int(input('ingresa la longitud del array'))
array_3 = np.ones(longitud)
print(array_3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [67]:
#crea un array con 15 números aletorios entre el 1 al 100 
array_4 = np.random.randint(1, 100, size=15)
print(array_4)

#multiplica todos los elementos de un array con un bucle
multiplicacion_1 = array_4[0]
for i in range(1,15):
    multiplicacion_1 *= array_4[i]
print(multiplicacion_1)
#ahora con una función de numpy
multiplicacion_2 = array_4.prod()
print(multiplicacion_2)
#valor mas alto del array 
maximo = np.max(array_4)
print(maximo)
#calcular media
media = np.mean(array_4)
print(media)
#mediana 
mediana = np.median(array_4)
print(mediana)
#desviación estamadar
des = np.std(array_4)
print(des)

[56 91 96 40 84 89 86 99 55  6 32 75 23 44 67]
1237319680
1237319680
99
62.86666666666667
67.0
28.03299643079364


C:\Users\volca\AppData\Local\Temp\ipykernel_7048\1867404388.py:8: RuntimeWarning: overflow encountered in scalar multiply
  multiplicacion_1 *= array_4[i]


In [65]:

#crear un array con 15 números aleatorios decimales entre el 0 y 1
array_5 = np.random.uniform(0,1, size=15)
print(array_5)
#sumar los elementos de ambos arrays con un operador 
suma_arrays1 = array_4 + array_5
print(suma_arrays1)
#ahora con numpy
suma_arrays2 = np.add(array_4, array_5)
print(f'suma arrays con np {suma_arrays2}')
#resta 
resta = np.subtract(array_4,array_5)
print(f'resta {resta}')
#multiplicacion
multi1 = array_4 * array_5
print(multi1)
# con np
multi2 = np.multiply(array_4,array_5)
print(multi2)

[0.6697342  0.713568   0.93042075 0.88094427 0.02228116 0.86948148
 0.87849531 0.14232813 0.45776097 0.25261023 0.54900564 0.1266343
 0.36480396 0.89730837 0.02258639]
[11.6697342  43.713568   91.93042075 19.88094427 96.02228116 43.86948148
 55.87849531 62.14232813 21.45776097 21.25261023 58.54900564 51.1266343
 60.36480396 82.89730837 45.02258639]
suma arrays con np [11.6697342  43.713568   91.93042075 19.88094427 96.02228116 43.86948148
 55.87849531 62.14232813 21.45776097 21.25261023 58.54900564 51.1266343
 60.36480396 82.89730837 45.02258639]
resta [10.3302658  42.286432   90.06957925 18.11905573 95.97771884 42.13051852
 54.12150469 61.85767187 20.54223903 20.74738977 57.45099436 50.8733657
 59.63519604 81.10269163 44.97741361]
[ 7.3670762  30.6834238  84.66828852 16.73794111  2.13899115 37.38770351
 48.31724209  8.82434419  9.61298045  5.30481491 31.84232711  6.45834954
 21.88823775 73.57928596  1.01638769]
[ 7.3670762  30.6834238  84.66828852 16.73794111  2.13899115 37.38770351
 