In [20]:
#crear un array lleno de 1s donde el usuario introduzca la longitud 
import numpy as np
longitud = 12 #int(input('Introduce la longitud del array: '))
array = np.ones(longitud)
print(array)
array2d = array.reshape(3,4)
print(array2d)
array2 = array2d.copy()
#concatenar los dos arrays 
arrays = np.concatenate([array2,array2d])
print('----------------------')
print(arrays)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
